### ISSUE TITLE
Simulations crashes - Errno2: mutation_table.dat

### ISSUE THREAD

**Issue by manuelsmendoza** [price0416/Simulome#1]
Hi!

I'm trying to use simulome to mutate the chromosomo 22 of human reference genome. I'm following simulome manual but it crashes with the following error: `[Errno 2] No such file or directory: 'mutation_table.dat'`

Does anyone know why it is happening?

```
 python $SIMULOME --genome=chr22.fa --anno=GRCh38_UCSC-REFSEQ_CHR22.gtf --output=testing --indel=2 --del_len=100 --del_distrib=TRUE --del_std_dev=50 --syn=TRUE --syn_percent=30 --syn_mean=10 --syn_std_dev=3 --duplicate=TRUE --percent_dup=10 --verbose=2
Reading FASTA files...
Reading annotation files...
Reading mutation files...
Error reading mutation table. Terminating execution.
[Errno 2] No such file or directory: 'mutation_table.dat'
```

**Comment by price0416** [comment]
Be sure that the mutation_table.dat file is in the same directory.  That file is found here:

https://github.com/price0416/Simulome/blob/master/mutation_table.dat
